name: Yura Hulpa blog
description: small tech blog
meta_description: "tech and fun"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://wolendranh.github.io/'
google_analytics: 'UA-82743800-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Yura Hulpa'
